In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array(range(1,4))

array([1, 2, 3])

In [5]:
A = np.array([[1,2,3], [4,5,6]])

In [6]:
A.shape

(2, 3)

In [7]:
A = np.array([[1,2], [3,4], [5,6]])

In [8]:
A.shape

(3, 2)

In [9]:
A = np.array([[1,2,3], [4,5,6]])

In [10]:
A.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
B = A.reshape(-1,2)

In [12]:
# 行追加
np.append(B, [[7,8]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
# 列追加
np.append(B, [[7], [8], [9]], axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [14]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
B[0][1]

2

In [16]:
B+B*3

array([[ 4,  8],
       [12, 16],
       [20, 24]])

In [18]:
# 行列の積
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [19]:
# 0〜1までの一様分布に従う乱数を生成
np.random.rand(3,2)

array([[0.01226916, 0.63106762],
       [0.24051849, 0.95874802],
       [0.29296563, 0.80021253]])

In [20]:
# 標準正規分布に従う乱数を生成
np.random.randn(3,2)

array([[ 0.55540225,  1.1903169 ],
       [-1.8343084 , -0.04224179],
       [-0.50660644, -0.58341871]])

In [21]:
A = np.array([1,2,3,4,5])

In [22]:
A

array([1, 2, 3, 4, 5])

In [23]:
np.sum(A)

15

In [24]:
np.mean(A)

3.0

In [25]:
np.max(A)

5

In [27]:
# 標準偏差
np.std(A)

1.4142135623730951

In [28]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
np.mean(B, axis=0)

array([3., 4.])

In [30]:
np.mean(B, axis=1)

array([1.5, 3.5, 5.5])